from datetime import time

MORNING_START = time(15, 0)
MORNING_END = time(16, 0)

EVENING_START = time(16, 0)  # 4 PM
EVENING_END = time(16, 30)   # 5:30 PM


MORNING_NOTIFY_HOUR = 10
MORNING_NOTIFY_MINUTE = 12

EVENING_NOTIFY_HOUR = 17
EVENING_NOTIFY_MINUTE = 12
